### PR TITLE
Move to hwtypes adt

### PR DESCRIPTION
**Pull request by cdonovick**

### CODE REVIEW

**Comment by cdonovick** [comment]
test_pico_encode is broken as the the bitfield encoder assumes an order of the Sum fields.

**Comment by rdaly525** [comment]
Is there anything preventing this from being merged?
Some of the latest metamapper changes require this change.

**Comment by leonardt** [comment]
Okay with me to merge, main thing is that we need to sync the merges on all repos (i think magma and lassen have related PRs)

**Comment by rdaly525** [comment]
@leonardt, I merged Lassen. Any magma dependencies with this merge?

**Comment by leonardt** [comment]
I merged the related magma and fault branches

**Pull request merged**
