### PR TITLE
Add Global type modifier

### PR DESCRIPTION
**Pull request by rsetaluri**
Depends on https://github.com/leonardt/hwtypes/pull/41

### CODE REVIEW

**Comment by cdonovick** [comment]
This seems like a garnet thing not a peak thing

**Comment by cdonovick** [comment]
Or more correctly a lassen thing rather than a core peak thing

**Comment by rsetaluri** [comment]
@cdonovick I think the creation of the modifier should be in peak. Lassen should then use it.

If we have another peak program (e.g. Diablo) they might want to use `Global` too and it should be the same type.

**Comment by cdonovick** [comment]
@rdaly525 what do you think?

**Comment by leonardt** [comment]
I missed the PR/discussion about `make_modifier` in the context of hwtypes, does this purely serve as an "annotation" on a type (e.g. this type is a `Global`) or does this add other functionality? (This would help me weigh in on whether this fits better in Peak or Lassen).

It seems like the notion of a `Global` type modifier could be either interpreted as a language level construct (this would imply having it in Peak), or as a design specific construct (this would imply having it in Lassen, and that other designs might eschew the use of a Global modifier)

**Comment by leonardt** [comment]
Addendum: it seems that @rsetaluri motivated use case is that two separate designs share a common global type modifier. Consider a generic pass in some infrastructure (say gemstome). It may operate on the notion of a `Global` type. Should this pass infrastructure special case `Global` for each design that it operates on? Seems like in this use case there is motivation to have a generic `Global` so that the pass can be generic over many designs

**Comment by cdonovick** [comment]
@leonardt make_modifier creates annotation It doesn't currently change the behavior of the underlying type in anyway.  hwtypes does not typecheck modifiers so `ModifiedBit1(ModifiedBit2(0))` will work fine.

We could add type checking if we want.  

For the nature of the annotations see
https://github.com/leonardt/hwtypes/blob/master/tests/test_modifiers.py

**Comment by rsetaluri** [comment]
@rdaly525 and I agreed this should move to lassen. Will PR there.

**Pull request closed without merging**
