### PR TITLE
Mapper

### PR DESCRIPTION
**Pull request by cdonovick**
Major rewrite of adt
Basic mapper

### CODE REVIEW

**Comment by cdonovick** [comment]
tagging @leonardt

**Comment by phanrahan** [comment]
I am reviewing this code now. 

When I run the tests, I get the following warnings:
```
=============================== warnings summary ===============================
tests/test_arm.py::test_and
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

tests/test_arm.py::test_eor
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

tests/test_arm.py::test_mov
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

tests/test_arm.py::test_add
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

tests/test_arm.py::test_ldr
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

tests/test_arm.py::test_str
  /Users/hanrahan/git/hwtypes/hwtypes/bit_vector.py:108: UserWarning: Truncating value from <class 'peak.adt.T[32]'> to <class 'peak.adt.T[8]'>
    warnings.warn('Truncating value from {} to {}'.format(type(value), type(self)))

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

Is this expected?

**Comment by phanrahan** [comment]
When we do the merge, let's move the pe examples outside of this directory. The old pe would go in a new repo diablo, and the new pe goes into lassen.

**Comment by phanrahan** [comment]
Looks good so far. All the user-level code (processor definitions and tests) seem very clean.

Nice tests!

I still don't understand all the adt stuff though.

We need to update whitney before we do the merge. Let's change the name of whitney to lassen when we do the upgrade.

**Comment by cdonovick** [comment]
The warnings are generated from constructing `BitVector[k](v : BitVector[j])` where `j > k`.   This implicitly a equivalent to `BitVector[k](v[:k])`.  While this behavior is allowed I figured it is better to raise warnings about truncation.

**Pull request merged**
